org.gradle.jvmargs=-Xmx2560M -XX:MaxMetaspaceSize=1024M -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# 允许在含非 ASCII 字符的路径下构建（本机用户名含中文）
android.overridePathCheck=true
